#!/usr/bin/expect

set PASSWORD [lindex $argv 2]
set IP [lindex $argv 1]
set NAME [lindex $argv 0]

log_user 0

spawn ssh $NAME@$IP
expect "password:" {send "$PASSWORD\r"}
expect "$ " {send "cd DAQ\r"}
expect "$ " {send "sudo ./Beaglebone_Encoder_DAQ Encoder1.bin Encoder2.bin IRIG1.bin IRIG2.bin\r"}
expect ": " {send "$PASSWORD\r"}

log_user 1
while {0 == 0} {
	expect "allyourbasearebelongtous" {send "echo hi\r"}
}
